import {t,useLocale} from './i18n';
'use client';
import {useMemo,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Download,ChevronLeft,ChevronRight} from 'lucide-react';
function flatten(value:unknown,path=''):Array<[string,string]>{if(value===null||value===undefined)return [];if(typeof value!=='object')return [[path,String(value)]];return Object.entries(value).flatMap(([k,v])=>flatten(v,path?`${path} / ${k}`:k));}
export default function ArchiveDialog({selected,onClose}:{selected:any;onClose:()=>void}){
 useLocale();
 const [query,setQuery]=useState(''),[page,setPage]=useState(0);
 const rows=useMemo(()=>selected?flatten(selected.data).filter(([k,v])=>`${k} ${v}`.toLowerCase().includes(query.toLowerCase())):[],[selected,query]);
 const save=()=>{const a=document.createElement('a'),u=URL.createObjectURL(new Blob([JSON.stringify(selected.data,null,2)],{type:'application/json'}));a.href=u;a.download=selected.id+'-results.json';a.click();URL.revokeObjectURL(u)};
 return <Dialog open={Boolean(selected)} onOpenChange={open=>{if(!open)onClose()}}><DialogContent className="modal" style={{padding:0,gap:0,display:'block',background:'white',maxWidth:1040}}>{selected&&<><div className="modal-head"><div><DialogTitle>{t(selected.title)}</DialogTitle><div className="source-line">{selected.source}</div></div></div><div className="modal-content"><DialogDescription className="side-note" style={{marginTop:0}}>{t(selected.scope)} {t("数值、区间和状态按原始汇总展示。")}</DialogDescription><div style={{display:'flex',gap:12,margin:'16px 0',flexWrap:'wrap'}}><input className="archive-search" aria-label={t("搜索结果指标")} placeholder={t("搜索指标、任务或条件")} value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}}/><button className="button" onClick={save}><Download size={15}/> {t("下载完整汇总")}</button></div><div className="table-wrap"><table className="numeric-table"><thead><tr><th>{t("指标 / 条件路径")}</th><th>{t("原始结果")}</th></tr></thead><tbody>{rows.slice(page*50,(page+1)*50).map(([k,v],i)=><tr key={`${k}-${i}`}><td>{k}</td><td>{v}</td></tr>)}</tbody></table></div><div className="archive-pagination"><span>{rows.length} {t("条结果 · 第")}{page+1} / {Math.max(1,Math.ceil(rows.length/50))} {t("页")}</span><div><button className="button" aria-label={t("结果上一页")} disabled={!page} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={16}/></button> <button className="button" aria-label={t("结果下一页")} disabled={(page+1)*50>=rows.length} onClick={()=>setPage(p=>p+1)}><ChevronRight size={16}/></button></div></div><div className="source-line">{t("来源 SHA-256：")}{selected.sha256}</div></div></>}</DialogContent></Dialog>;
}
