'use client';
import {useMemo,useState} from 'react';
import DatasetSummary from './datasets/summary';
const pct=(v:number|undefined)=>v===undefined?'—':`${(v*100).toFixed(1)}%`;
const families:Record<string,string>={T1:'T1 场所变化与行程重规划',T2:'T2 家庭照料与记忆',T3:'T3 团队审核与耦合约束',T4:'T4 多跳核验与传播',T5:'T5 城市政策与权限',L1:'L1 中断与接替'};
const games:Record<string,string>={bomb_boxes:'炸弹风险任务',trust_invest:'信任博弈 · 投资',dictator_give:'独裁者博弈',ultimatum_accept:'最后通牒 · 接受阈值',pgg_g10:'公共品 · 10人',ultimatum_offer:'最后通牒 · 提议',pgg_g4:'公共品 · 4人',trust_return50:'信任博弈 · 返还'};
const model=(s:string)=>s.replace('zhipu:','').replace('glm-','GLM-');
export default function HistoricalBoard({archives}:{archives:any[]}){
 const [axis,setAxis]=useState('functional'),[family,setFamily]=useState('T1'),[track,setTrack]=useState('full'),[game,setGame]=useState('dictator_give');
 const functional=archives.find(a=>a.source==='results/formal/functional_results.json')?.data;
 const human=archives.find(a=>a.source==='results/formal/human_results.json')?.data;
 const tracks=useMemo(()=>[...new Set(Object.keys(functional?.by_cell||{}).filter(k=>k.split('|')[1]===family).map(k=>k.split('|')[2]))].sort(),[functional,family]);
 const rows=useMemo(()=>axis==='functional'?Object.entries(functional?.by_cell||{}).filter(([key])=>{const x=key.split('|');return x[1]===family&&x[2]===track}).map(([key,v])=>({key,parts:key.split('|'),v:v as any})):Object.entries(human||{}).filter(([,v])=>(v as any).H2?.[game]).map(([key,v])=>({key,parts:key.split('|'),v:(v as any).H2[game]})),[functional,human,axis,family,track,game]);
 if(!functional&&!human)return null;
 return <section className="panel" style={{marginBottom:22}}><div className="axis-tabs"><button className={axis==='functional'?'active':''} onClick={()=>setAxis('functional')}>历史 FOS · 功能机制</button><button className={axis==='human'?'active':''} onClick={()=>setAxis('human')}>历史 FOS · 人类效度</button></div><div className="board-controls"><div className="filters">{axis==='functional'?<><div className="field"><label htmlFor="old-family">任务族</label><select id="old-family" value={family} onChange={e=>{setFamily(e.target.value);setTrack('full')}}>{Object.entries(families).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div><div className="field"><label htmlFor="old-track">实验轨道</label><select id="old-track" value={track} onChange={e=>setTrack(e.target.value)}>{tracks.map(t=><option key={t} value={t}>{t}</option>)}</select></div></>:<div className="field"><label htmlFor="old-game">行为实验</label><select id="old-game" value={game} onChange={e=>setGame(e.target.value)}>{Object.entries(games).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div>}<span className="tag" style={{alignSelf:'end',justifySelf:'start'}}>历史冻结协议 · 独立展示</span></div></div><DatasetSummary id={axis==='functional'?'FOS-'+family:'PNAS-'+game}/><div className="table-wrap"><table><thead><tr>{axis==='functional'?<><th>模型</th><th>条件</th><th>结果正确率 R2</th><th>完整通过 FullPass</th><th>有效 / 总运行</th><th>FullPass 区间</th></>:<><th>模型</th><th>人设配置</th><th>Wasserstein 距离 ↓</th><th>人类噪声下界</th><th>有效 / 总抽样</th><th>距离区间</th></>}</tr></thead><tbody>{rows.map(r=><tr key={r.key}>{axis==='functional'?<><td>{model(r.parts[0])}</td><td>{r.parts[3]==='control'?'基准条件':'变化条件'}</td><td>{pct(r.v.R2?.rate)}</td><td><strong>{pct(r.v.FullPass?.rate)}</strong></td><td>{r.v.FullPass?.den} / {r.v.FullPass?.n_cells}</td><td>{r.v.FullPass?.ci?.map((x:number)=>pct(x)).join(' – ')||'—'}</td></>:<><td>{model(r.parts[0])}</td><td>{r.parts[1]}</td><td><strong>{r.v.w1_norm?.toFixed(3)||'—'}</strong></td><td>{r.v.human_floor?.toFixed(3)||'—'}</td><td>{r.v.n_valid} / {r.v.n_total}</td><td>{r.v.w1_ci?.map((x:number)=>x.toFixed(3)).join(' – ')||'—'}</td></>}</tr>)}</tbody></table></div><div className="table-note">{axis==='functional'?'完整通过要求结果和证据过程均通过。测量无效单元不计入有效分母，并保留失效率。这里展示原始冻结版本；A7 修订及后续标准任务结果见下方完整结果库。':'这是历史 H2 分布比较，不是当前原生三系统问答轮。人设、模型和温度沿用原始协议；距离不能与准确率相加。'}</div></section>;
}
