'use client';
import {useEffect,useMemo,useState} from 'react';
import {BookOpen,Search,Download,ExternalLink,FileCode2,Info,ChevronDown} from 'lucide-react';
import catalog from './catalog.json';
import DatasetSummary,{datasetInfo,datasetLabel,datasetDescriptions,PsychExperimentDirectory} from '../datasets/summary';
const methodItems=catalog.items;
const GROUPS=['全部','数学','问答','知识与推理','代码与工具','长期记忆','人类问卷','行为博弈','心理实验','历史FOS','待接入'];
const fmt=(n:number)=>n.toLocaleString('en-US');
function download(){const a=document.createElement('a'),u=URL.createObjectURL(new Blob([JSON.stringify({...catalog,datasetDescriptions},null,2)],{type:'application/json'}));a.href=u;a.download='FOS-Bench-methods-and-scoring.json';a.click();URL.revokeObjectURL(u);}
function Part({title,children}:{title:string;children:React.ReactNode}){return <section className="method-part"><h3>{title}</h3>{children}</section>}
function Bullet({items}:{items:string[]}){return <ul className="method-bullets">{items.map((s,i)=><li key={i}>{s}</li>)}</ul>}
export default function MethodsGuide({initialBenchmark='GSM8K',currentDatasets=[]}:{initialBenchmark?:string;currentDatasets?:string[]}){
 const [group,setGroup]=useState('全部'),[query,setQuery]=useState(''),[selected,setSelected]=useState(methodItems.some(i=>i.id===initialBenchmark)?initialBenchmark:'GSM8K'),[rules,setRules]=useState(false);
 const filtered=useMemo(()=>methodItems.filter(i=>(group==='全部'||i.group===group)&&[i.id,i.title,i.purpose,datasetInfo(i.id)?.label,datasetInfo(i.id)?.about,datasetInfo(i.id)?.action,i.scoreName,i.formula,...i.scoring].join(' ').toLowerCase().includes(query.toLowerCase())),[group,query]);
 const item=methodItems.find(i=>i.id===selected)||methodItems[0];
 useEffect(()=>{if(methodItems.some(i=>i.id===initialBenchmark)){setSelected(initialBenchmark);setGroup('全部');setQuery('')}},[initialBenchmark]);
 const select=(id:string)=>{setSelected(id);const u=new URL(window.location.href);u.searchParams.set('view','method');u.searchParams.set('bench',id);window.history.replaceState(null,'',u.pathname+u.search+u.hash)};
 const missing=currentDatasets.filter(ds=>!methodItems.some(i=>i.id===ds));
 return <section className="method-library">
 <div className="method-library-head"><div><h2>逐项数据集介绍与评分说明</h2><p>59个当前测试条件 · 18类历史协议 · 2项待接入。按实际冻结输入和评分器逐项解释。</p></div><button className="button" onClick={download}><Download size={15}/> 下载方法说明</button></div>
 <div className="method-library-rule"><Info size={17}/><p>题目数、预测条目、行为抽样和实验cell是不同单位。每项都保留自己的指标、版本及分母。</p><button className="button" onClick={()=>setRules(v=>!v)} aria-expanded={rules}>{rules?'收起共同规则':'共同规则与公式'}<ChevronDown size={15}/></button></div>
 {missing.length>0&&<div className="error-banner">新增结果尚待补充方法：{missing.join('、')}。不从测试集名称猜测评分规则。</div>}
 {rules&&<div className="method-common"><CommonRules/></div>}
 <div className="method-library-layout"><aside className="method-index" aria-label="评测方法目录"><div className="method-search"><Search size={16}/><input aria-label="搜索评测方法" placeholder="搜索 benchmark、EM、F1…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="field"><label htmlFor="method-group">评测类别</label><select id="method-group" value={group} onChange={e=>setGroup(e.target.value)}>{GROUPS.map(g=><option key={g} value={g}>{g}</option>)}</select></div><div className="method-index-count">{filtered.length}项方法说明</div><div className="method-index-list">{filtered.map(i=><button key={i.id} className={selected===i.id?'selected':''} onClick={()=>select(i.id)} aria-pressed={selected===i.id}><span>{i.title}</span><small>{datasetInfo(i.id)?.label||i.group}</small></button>)}</div><select className="method-mobile-select" aria-label="选择benchmark方法" value={filtered.some(i=>i.id===selected)?selected:''} onChange={e=>select(e.target.value)}><option value="" disabled>选择一个benchmark</option>{filtered.map(i=><option key={i.id} value={i.id}>{datasetLabel(i.id)}</option>)}</select>{!filtered.length&&<p className="side-note">没有匹配项，尝试测试集名称或评分指标。</p>}</aside>
 <article className="panel method-detail" aria-labelledby="method-detail-title"><div className="method-detail-head"><div className="method-detail-tags"><span className="tag accent">{item.group}</span><span className="tag">{item.badge}</span><span className="tag">{item.protocol}</span></div><h2 id="method-detail-title">{item.title}</h2><p>{item.purpose}</p><div className="method-sample-line">{'sample' in item&&item.sample!==undefined&&<span>本轮配额 <strong>{fmt(item.sample as number)}</strong> {'sampleUnit' in item?String(item.sampleUnit):'题 / 每个系统×模型'}</span>}{'sourceCount' in item&&item.sourceCount!==undefined&&<span>冻结源池 <strong>{fmt(item.sourceCount as number)}</strong></span>}{'sourceSplit' in item&&<span>源划分 <strong>{String(item.sourceSplit)}</strong></span>}{'surveyWave' in item&&<span>波次 <strong>{String(item.surveyWave)}</strong></span>}</div></div>
 <div className="method-detail-body"><DatasetSummary id={item.id}/>{item.id==='Psych-101'&&<PsychExperimentDirectory/>}<Part title="本轮冻结输入与数据版本"><p>{item.input}</p></Part><Part title="实际评测过程"><ol className="method-steps">{item.execution.map((s,i)=><li key={i}><span>{i+1}</span><p>{s}</p></li>)}</ol></Part><Part title="主指标：如何得到这个分数"><div className="method-score-label">{item.scoreName}</div><pre className="method-formula">{item.formula}</pre><Bullet items={item.scoring}/></Part><Part title="分母和失败如何处理"><div className="method-denominator">{item.denominator}</div><p>{item.failure}</p><p className="method-subtle">“格式失败”列沿用平台/提取器记录；某些数值或结构错误会计为答错，但不一定增加该列。判断结果须同时看主分、分母与原始失败记录。</p></Part>
 {item.extras.length>0&&<Part title="辅助指标与版本区别"><Bullet items={item.extras}/></Part>}
 {'cohorts' in item&&item.cohorts&&<Part title="本调查的冻结配额与方法资格"><p>下表按方法与划分展开。同一行样本给九种系统×模型组合重复测试；条目数不等于不同受访者人数。</p><div className="table-wrap"><table className="method-cohort-table"><thead><tr><th>划分</th><th>提示方法</th><th>每个配置的预测配额</th></tr></thead><tbody>{(item.cohorts as Array<{split:string;method:string;sample:number}>).map((r,i)=><tr key={i}><td>{r.split}</td><td>{r.method}</td><td>{r.sample}</td></tr>)}</tbody></table></div></Part>}
 {item.example&&<Part title="评分示例（不是实验成绩）"><div className="method-example">{item.example}</div></Part>}
 {item.limits.length>0&&<Part title="这个成绩能支持哪些结论"><Bullet items={item.limits}/></Part>}
 <Part title="来源与可复核评分器"><div className="method-ref-list">{item.references.map((r,i)=><a key={i} href={r.url} target="_blank" rel="noreferrer">{r.name}<ExternalLink size={14}/></a>)}</div><div className="method-code-list">{item.implementation.map((s,i)=><div key={i}><FileCode2 size={15}/><code>{s}</code></div>)}</div><p className="method-subtle">按冻结数据与保存的评分代码编写。本页没有重新生成答案，也没有改变原实验成绩。</p></Part>
 </div></article></div>
 <details className="method-version-box"><summary><FileCode2 size={16}/> 评分实现快照与 SHA-256</summary><p className="side-note">说明对应的本地评分文件快照，可用于复核后续规则变更。网页更新时间与实验运行时间分别报告。</p>{catalog.scorerVersions.map(v=><div key={v.file}><strong>{v.file}</strong><code>{v.sha256}</code></div>)}</details>
 </section>
}
function CommonRules(){return <>
 <div className="method-common-grid"><section><h3>当前原生问答轮 A35 / A36</h3><p>固定seed42，常规输入总数2000，按源题量比例分配，每个条件至少30题；集内按可用学科、难度或类别分层。另有记忆300题、问卷1500条、博弈300次输入，总计4100个输入，三个系统×三个模型展开为36,900项。</p><p>三个入口是GAWorld访谈、YuLan-OneSim交互和AgentSociety2问答。保留各自声明的记忆与解析；AS2配置最多4轮ReAct与空任务环境，OneSim采用ListStrategy，GAWorld采用访谈/回忆流程。它们不是三个完整多天城市仿真的验收。</p><p>普通题、记忆和问卷温度0；博弈沿登记温度/人设抽样。GLM低推理强度、Qwen3.5-27B Q4、每单元独立缓存等配置固定。只改变调度与GPU副本，不依据分数挑题。</p></section><section><h3>分母、缺失和配对</h3><p>已观察的错误、原生解析/finish失败保留计错；缺失的服务响应或无效裁判标签保持未完成。仅当整个配额均评分后给“完整样本分数”。不把请求次数当题目数，也不把九种配置当九倍独立统计样本。</p><p>旧FOS冻结工作流先过R0门，原始能力比例只在R0有效cell上计算，并另报失效率；A35把已观察的原生流程失败作为任务失败。两种版本规则不能混用。</p><p>同题跨系统、模型和机制条件是配对数据；FRAMES两个条件、MAB中的LongMemEval子集等可能共享题源，不能相加宣称新的独立复制。</p></section></div>
 <section className="method-common-formulas"><h3>统计与辅助分布指标</h3><div><strong>分层加权估计</strong><code>Σₕ (源层题量Nₕ / ΣNₕ) × 该层样本得分均值</code><p>任务/记忆样本完成后另外保存。榜单当前主分是原始样本均值，不能将其标为总体全量成绩。</p></div><div><strong>S²Bench 辅助指标</strong><code>F1ₖ = 2TPₖ/(2TPₖ+FPₖ+FNₖ)；macro-F1 = meanₖ F1ₖ；weighted-F1 = Σₖ 人类该类比例 × F1ₖ</code><code>JS = ½KL(p‖m)+½KL(q‖m), m=(p+q)/2；TV = ½Σ|pₖ−qₖ|</code><p>逐题按真实选项语义算分布；无效预测单列一类。JS用自然对数；KL分别报告两个方向，以10⁻¹²平滑后归一化。有序选项才使用MAE/EMD，序数EMD按累积比例差求和、除以K−1归一化。当前原生榜单主要展示Accuracy，这些定义不代表官方分数已取得。</p></div><div><strong>历史 F1–F5 与 R0–R3</strong><p>F1任务结果、F2配对关键决策、F3送达/采用/交接及权限、F4 Direct−Full传播损失、F5等预算Multi−Single净收益。R0测量有效、R1agent来源、R2结果正确、R3过程证据。通过最终结果并不自动通过证据链。</p></div><div><strong>两条轴与不确定性</strong><p>功能正确率和人类分布距离分别报告，不合成总分。小样本点排名只描述冻结样本。当前原生轮不声称已完成正式聚类置信区间；历史功能区间、H2/H3/H7区间按各自保存协议解释。</p></div></section>
 </>}
